ALTER TABLE CorteCor_Pessoa ADD 
    IsCliente BIT NULL DEFAULT 1,
    IsFornecedor BIT NULL DEFAULT 0,
    IsTransportador BIT NULL DEFAULT 0,
    NomeContato VARCHAR(150) NULL,
    Pais VARCHAR(100) NULL,
    IdEstrangeiro VARCHAR(100) NULL,
    EntCep VARCHAR(20) NULL,
    EntUf VARCHAR(2) NULL,
    EntCidade VARCHAR(100) NULL,
    EntNome VARCHAR(150) NULL,
    EntCpfCnpj VARCHAR(20) NULL,
    EntInscricaoEstadual VARCHAR(50) NULL,
    EntLogradouro VARCHAR(150) NULL,
    EntNumero VARCHAR(20) NULL,
    EntComplemento VARCHAR(100) NULL,
    EntBairro VARCHAR(100) NULL,
    EntEmail VARCHAR(150) NULL,
    EntTelefone VARCHAR(20) NULL,
    ConsumidorFinal BIT NULL DEFAULT 0,
    IndicadorIE INT NULL,
    IESubstTrib VARCHAR(50) NULL,
    Suframa VARCHAR(50) NULL,
    Tags VARCHAR(255) NULL,
    DataComemorativa DATE NULL,
    DescricaoComemoracao VARCHAR(200) NULL,
    BasesLegais VARCHAR(MAX) NULL,
    Observacoes VARCHAR(MAX) NULL;
