namespace CorteCor.Handlers;

public static class Lc116ItensCatalogo
{
    public static readonly (string Codigo, string Descricao)[] Itens =
    {
        ("01.01", "Análise e desenvolvimento de sistemas."),
        ("01.02", "Programação."),
        ("01.03", "Processamento, armazenamento ou hospedagem de dados, textos, imagens, vídeos, páginas eletrônicas, aplicativos e sistemas de informação, entre outros formatos, e congêneres."),
        ("01.04", "Elaboração de programas de computadores, inclusive de jogos eletrônicos, independentemente da arquitetura construtiva da máquina em que o programa será executado."),
        ("01.05", "Licenciamento ou cessão de direito de uso de programas de computação."),
        ("01.06", "Assessoria e consultoria em informática."),
        ("01.07", "Suporte técnico em informática, inclusive instalação, configuração e manutenção de programas de computação e bancos de dados."),
        ("01.08", "Planejamento, confecção, manutenção e atualização de páginas eletrônicas."),
        ("01.09", "Disponibilização, sem cessão definitiva, de conteúdos de áudio, vídeo, imagem e texto por meio da internet, respeitada a imunidade de livros, jornais e periódicos."),
        ("02.01", "Serviços de pesquisas e desenvolvimento de qualquer natureza."),
        ("03.02", "Cessão de direito de uso de marcas e de sinais de propaganda."),
        ("03.03", "Exploração de salões de festas, centros de convenções, escritórios virtuais, stands, quadras esportivas, auditórios, casas de espetáculos, parques de diversões e congêneres."),
        ("03.04", "Locação, sublocação, arrendamento, direito de passagem ou permissão de uso, compartilhado ou não, de ferrovia, rodovia, postes, cabos, dutos e condutos."),
        ("03.05", "Cessão de andaimes, palcos, coberturas e outras estruturas de uso temporário."),
        ("04.01", "Medicina e biomedicina."),
        ("04.02", "Análises clínicas, patologia, eletricidade médica, radioterapia, quimioterapia, ultrassonografia, ressonância magnética, radiologia, tomografia e congêneres."),
        ("04.03", "Hospitais, clínicas, laboratórios, sanatórios, manicômios, casas de saúde, prontos-socorros, ambulatórios e congêneres."),
        ("04.04", "Instrumentação cirúrgica."),
        ("04.05", "Acupuntura."),
        ("04.06", "Enfermagem, inclusive serviços auxiliares."),
        ("04.07", "Serviços farmacêuticos."),
        ("04.08", "Terapia ocupacional, fisioterapia e fonoaudiologia."),
        ("04.09", "Terapias de qualquer espécie destinadas ao tratamento físico, orgânico e mental."),
        ("04.10", "Nutrição."),
        ("04.11", "Obstetrícia."),
        ("04.12", "Odontologia."),
        ("04.13", "Ortóptica."),
        ("04.14", "Próteses sob encomenda."),
        ("04.15", "Psicanálise."),
        ("04.16", "Psicologia."),
        ("04.17", "Casas de repouso e de recuperação, creches, asilos e congêneres."),
        ("04.18", "Inseminação artificial, fertilização in vitro e congêneres."),
        ("04.19", "Bancos de sangue, leite, pele, olhos, óvulos, sêmen e congêneres."),
        ("04.20", "Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie."),
        ("04.21", "Unidade de atendimento, assistência ou tratamento móvel e congêneres."),
        ("04.22", "Planos de medicina de grupo ou individual e convênios para prestação de assistência médica, hospitalar, odontológica e congêneres."),
        ("04.23", "Outros planos de saúde prestados por terceiros contratados, credenciados, cooperados ou pagos pelo operador do plano mediante indicação do beneficiário."),
        ("05.01", "Medicina veterinária e zootecnia."),
        ("05.02", "Hospitais, clínicas, ambulatórios, prontos-socorros e congêneres na área veterinária."),
        ("05.03", "Laboratórios de análise na área veterinária."),
        ("05.04", "Inseminação artificial, fertilização in vitro e congêneres."),
        ("05.05", "Bancos de sangue e de órgãos e congêneres."),
        ("05.06", "Coleta de sangue, leite, tecidos, sêmen, órgãos e materiais biológicos de qualquer espécie."),
        ("05.07", "Unidade de atendimento, assistência ou tratamento móvel e congêneres."),
        ("05.08", "Guarda, tratamento, amestramento, embelezamento, alojamento e congêneres."),
        ("05.09", "Planos de atendimento e assistência médico-veterinária."),
        ("06.01", "Barbearia, cabeleireiros, manicuros, pedicuros e congêneres."),
        ("06.02", "Esteticistas, tratamento de pele, depilação e congêneres."),
        ("06.03", "Banhos, duchas, sauna, massagens e congêneres."),
        ("06.04", "Ginástica, dança, esportes, natação, artes marciais e demais atividades físicas."),
        ("06.05", "Centros de emagrecimento, spa e congêneres."),
        ("06.06", "Aplicação de tatuagens, piercings e congêneres."),
        ("07.01", "Engenharia, agronomia, agrimensura, arquitetura, geologia, urbanismo, paisagismo e congêneres."),
        ("07.02", "Execução de obras de construção civil, hidráulica ou elétrica e obras semelhantes, inclusive sondagem, perfuração de poços, drenagem, terraplanagem, pavimentação e montagem."),
        ("07.03", "Elaboração de planos diretores, estudos de viabilidade, estudos organizacionais, anteprojetos, projetos básicos e executivos relacionados com engenharia."),
        ("07.04", "Demolição."),
        ("07.05", "Reparação, conservação e reforma de edifícios, estradas, pontes, portos e congêneres."),
        ("07.06", "Colocação e instalação de tapetes, carpetes, assoalhos, cortinas, revestimentos, vidros, divisórias, placas de gesso e congêneres."),
        ("07.07", "Recuperação, raspagem, polimento e lustração de pisos e congêneres."),
        ("07.08", "Calafetação."),
        ("07.09", "Varrição, coleta, remoção, incineração, tratamento, reciclagem, separação e destinação final de lixo, rejeitos e resíduos quaisquer."),
        ("07.10", "Limpeza, manutenção e conservação de vias e logradouros públicos, imóveis, chaminés, piscinas, parques, jardins e congêneres."),
        ("07.11", "Decoração e jardinagem, inclusive corte e poda de árvores."),
        ("07.12", "Controle e tratamento de efluentes de qualquer natureza e de agentes físicos, químicos e biológicos."),
        ("07.13", "Dedetização, desinfecção, desinsetização, imunização, higienização, desratização, pulverização e congêneres."),
        ("07.16", "Florestamento, reflorestamento, semeadura, adubação, reparação de solo, plantio, silagem, colheita, silvicultura, exploração florestal e congêneres."),
        ("07.17", "Escoramento, contenção de encostas e serviços congêneres."),
        ("07.18", "Limpeza e dragagem de rios, portos, canais, baías, lagos, lagoas, represas, açudes e congêneres."),
        ("07.19", "Acompanhamento e fiscalização da execução de obras de engenharia, arquitetura e urbanismo."),
        ("07.20", "Aerofotogrametria, cartografia, mapeamento, levantamentos topográficos, batimétricos, geográficos, geodésicos, geológicos e congêneres."),
        ("07.21", "Pesquisa, perfuração, cimentação, mergulho, perfilagem, concretagem e outros serviços relacionados com exploração de petróleo, gás natural e recursos minerais."),
        ("07.22", "Nucleação e bombardeamento de nuvens e congêneres."),
        ("08.01", "Ensino regular pré-escolar, fundamental, médio e superior."),
        ("08.02", "Instrução, treinamento, orientação pedagógica e educacional, avaliação de conhecimentos de qualquer natureza."),
        ("09.01", "Hospedagem de qualquer natureza em hotéis, apart-service, flat, apart-hotéis, motéis, pensões e congêneres; ocupação por temporada com serviço."),
        ("09.02", "Agenciamento, organização, promoção, intermediação e execução de programas de turismo, passeios, viagens, excursões, hospedagens e congêneres."),
        ("09.03", "Guias de turismo."),
        ("10.01", "Agenciamento, corretagem ou intermediação de câmbio, seguros, cartões de crédito, planos de saúde e previdência privada."),
        ("10.02", "Agenciamento, corretagem ou intermediação de títulos em geral, valores mobiliários e contratos quaisquer."),
        ("10.03", "Agenciamento, corretagem ou intermediação de direitos de propriedade industrial, artística ou literária."),
        ("10.04", "Agenciamento, corretagem ou intermediação de contratos de arrendamento mercantil, franquia e faturização."),
        ("10.05", "Agenciamento, corretagem ou intermediação de bens móveis ou imóveis não abrangidos em outros itens, inclusive em bolsas de mercadorias e futuros."),
        ("10.06", "Agenciamento marítimo."),
        ("10.07", "Agenciamento de notícias."),
        ("10.08", "Agenciamento de publicidade e propaganda, inclusive agenciamento de veiculação por quaisquer meios."),
        ("10.09", "Representação de qualquer natureza, inclusive comercial."),
        ("10.10", "Distribuição de bens de terceiros."),
        ("11.01", "Guarda e estacionamento de veículos terrestres automotores, aeronaves e embarcações."),
        ("11.02", "Vigilância, segurança ou monitoramento de bens, pessoas e semoventes."),
        ("11.03", "Escolta, inclusive de veículos e cargas."),
        ("11.04", "Armazenamento, depósito, carga, descarga, arrumação e guarda de bens de qualquer espécie."),
        ("11.05", "Monitoramento e rastreamento a distância de veículos, cargas, pessoas e semoventes em circulação ou movimento, por telefonia móvel, satélite, rádio ou outros meios."),
        ("12.01", "Espetáculos teatrais."),
        ("12.02", "Exibições cinematográficas."),
        ("12.03", "Espetáculos circenses."),
        ("12.04", "Programas de auditório."),
        ("12.05", "Parques de diversões, centros de lazer e congêneres."),
        ("12.06", "Boates, taxi-dancing e congêneres."),
        ("12.07", "Shows, ballet, danças, desfiles, bailes, óperas, concertos, recitais, festivais e congêneres."),
        ("12.08", "Feiras, exposições, congressos e congêneres."),
        ("12.09", "Bilhares, boliches e diversões eletrônicas ou não."),
        ("12.10", "Corridas e competições de animais."),
        ("12.11", "Competições esportivas ou de destreza física ou intelectual, com ou sem participação do espectador."),
        ("12.12", "Execução de música."),
        ("12.13", "Produção de eventos, espetáculos, entrevistas, shows, ballet, danças, desfiles, bailes, teatros, óperas, concertos, recitais, festivais e congêneres."),
        ("12.14", "Fornecimento de música para ambientes fechados ou não, mediante transmissão por qualquer processo."),
        ("12.15", "Desfiles de blocos carnavalescos ou folclóricos, trios elétricos e congêneres."),
        ("12.16", "Exibição de filmes, entrevistas, musicais, espetáculos, shows, concertos, desfiles, óperas e competições esportivas ou intelectuais."),
        ("12.17", "Recreação e animação, inclusive em festas e eventos de qualquer natureza."),
        ("13.02", "Fonografia ou gravação de sons, inclusive trucagem, dublagem, mixagem e congêneres."),
        ("13.03", "Fotografia e cinematografia, inclusive revelação, ampliação, cópia, reprodução, trucagem e congêneres."),
        ("13.04", "Reprografia, microfilmagem e digitalização."),
        ("13.05", "Composição gráfica, inclusive confecção de impressos gráficos, fotocomposição, clicheria, zincografia, litografia, fotolitografia e congêneres."),
        ("14.01", "Lubrificação, limpeza, revisão, conserto, restauração, manutenção e conservação de máquinas, veículos, aparelhos, motores, elevadores ou objetos."),
        ("14.02", "Assistência técnica."),
        ("14.03", "Recondicionamento de motores."),
        ("14.04", "Recauchutagem ou regeneração de pneus."),
        ("14.05", "Restauração, recondicionamento, pintura, beneficiamento, lavagem, secagem, tingimento, galvanoplastia, anodização, corte, polimento e congêneres."),
        ("14.06", "Instalação e montagem de aparelhos, máquinas e equipamentos, inclusive montagem industrial, prestadas ao usuário final com material por ele fornecido."),
        ("14.07", "Colocação de molduras e congêneres."),
        ("14.08", "Encadernação, gravação e douração de livros, revistas e congêneres."),
        ("14.09", "Alfaiataria e costura, quando o material for fornecido pelo usuário final, exceto aviamento."),
        ("14.10", "Tinturaria e lavanderia."),
        ("14.11", "Tapeçaria e reforma de estofamentos em geral."),
        ("14.12", "Funilaria e lanternagem."),
        ("14.13", "Carpintaria e serralheria."),
        ("14.14", "Guincho intramunicipal, guindaste e içamento."),
        ("15.01", "Administração de fundos, consórcios, cartões de crédito ou débito, carteiras de clientes, cheques pré-datados e congêneres."),
        ("15.02", "Abertura e manutenção de contas em geral, inclusive conta-corrente, investimentos, aplicação e poupança, no País e no exterior."),
        ("15.03", "Locação e manutenção de cofres particulares, terminais eletrônicos, terminais de atendimento, bens e equipamentos em geral."),
        ("15.04", "Fornecimento ou emissão de atestados em geral, inclusive atestado de idoneidade e capacidade financeira."),
        ("15.05", "Cadastro, elaboração de ficha cadastral, renovação cadastral e congêneres, inclusão ou exclusão em bancos cadastrais."),
        ("15.06", "Emissão, reemissão e fornecimento de avisos, comprovantes e documentos; coleta e entrega de documentos, bens e valores; serviços bancários correlatos."),
        ("15.07", "Acesso, movimentação, atendimento e consulta a contas por qualquer meio, inclusive terminais; fornecimento de saldo, extrato e informações."),
        ("15.08", "Serviços relativos a contratos de crédito, estudo, análise e avaliação de operações, aval, fiança, anuência e abertura de crédito."),
        ("15.09", "Arrendamento mercantil, inclusive cessão de direitos e obrigações, garantias, alterações, cancelamentos e registros relacionados ao leasing."),
        ("15.10", "Serviços relacionados a cobranças, recebimentos ou pagamentos de títulos, contas, carnês, câmbio, tributos e por conta de terceiros."),
        ("15.11", "Devolução de títulos, protesto, sustação de protesto, manutenção, reapresentação e demais serviços relacionados a títulos."),
        ("15.12", "Custódia em geral, inclusive de títulos e valores mobiliários."),
        ("15.13", "Serviços relacionados a operações de câmbio, contratos de câmbio, registros, cobrança ou depósito no exterior, cheques de viagem e cartas de crédito."),
        ("15.14", "Fornecimento, emissão, reemissão, renovação e manutenção de cartão magnético, cartão de crédito, débito, salário e congêneres."),
        ("15.15", "Compensação de cheques e títulos; serviços relacionados a depósito e saque de contas por qualquer meio."),
        ("15.16", "Ordens de pagamento, ordens de crédito, transferências de valores, dados, fundos, pagamentos e similares, inclusive entre contas."),
        ("15.17", "Emissão, fornecimento, devolução, sustação, cancelamento e oposição de cheques avulsos ou por talão."),
        ("15.18", "Serviços relacionados a crédito imobiliário, avaliação, vistoria, análise técnica e jurídica, contratos e termo de quitação."),
        ("16.01", "Serviços de transporte coletivo municipal rodoviário, metroviário, ferroviário e aquaviário de passageiros."),
        ("16.02", "Outros serviços de transporte de natureza municipal."),
        ("17.01", "Assessoria ou consultoria de qualquer natureza; análise, exame, pesquisa, coleta, compilação e fornecimento de dados e informações."),
        ("17.02", "Datilografia, digitação, estenografia, expediente, secretaria, resposta audível, redação, edição, interpretação, revisão, tradução e congêneres."),
        ("17.03", "Planejamento, coordenação, programação ou organização técnica, financeira ou administrativa."),
        ("17.04", "Recrutamento, agenciamento, seleção e colocação de mão-de-obra."),
        ("17.05", "Fornecimento de mão-de-obra, mesmo em caráter temporário, inclusive empregados, trabalhadores avulsos ou temporários."),
        ("17.06", "Propaganda e publicidade, inclusive promoção de vendas, planejamento de campanhas, elaboração de desenhos, textos e materiais publicitários."),
        ("17.08", "Franquia (franchising)."),
        ("17.09", "Perícias, laudos, exames técnicos e análises técnicas."),
        ("17.10", "Planejamento, organização e administração de feiras, exposições, congressos e congêneres."),
        ("17.11", "Organização de festas e recepções; bufê."),
        ("17.12", "Administração em geral, inclusive de bens e negócios de terceiros."),
        ("17.13", "Leilão e congêneres."),
        ("17.14", "Advocacia."),
        ("17.15", "Arbitragem de qualquer espécie, inclusive jurídica."),
        ("17.16", "Auditoria."),
        ("17.17", "Análise de Organização e Métodos."),
        ("17.18", "Atuária e cálculos técnicos de qualquer natureza."),
        ("17.19", "Contabilidade, inclusive serviços técnicos e auxiliares."),
        ("17.20", "Consultoria e assessoria econômica ou financeira."),
        ("17.21", "Estatística."),
        ("17.22", "Cobrança em geral."),
        ("17.23", "Assessoria, análise, avaliação, atendimento, consulta, cadastro, seleção, gerenciamento de informações e administração de contas a receber ou pagar."),
        ("17.24", "Apresentação de palestras, conferências, seminários e congêneres."),
        ("17.25", "Inserção de textos, desenhos e outros materiais de propaganda e publicidade em qualquer meio, exceto livros, jornais, periódicos e radiodifusão livre."),
        ("18.01", "Serviços de regulação de sinistros vinculados a contratos de seguros; inspeção e avaliação de riscos; prevenção e gerência de riscos seguráveis."),
        ("19.01", "Distribuição e venda de bilhetes e demais produtos de loteria, bingos, cartões, pules, cupons de apostas, sorteios, prêmios e congêneres."),
        ("20.01", "Serviços portuários, ferroportuários, utilização de porto, movimentação de passageiros e mercadorias, armazenagem, logística e congêneres."),
        ("20.02", "Serviços aeroportuários, utilização de aeroporto, movimentação de passageiros, armazenagem, movimentação de aeronaves, logística e congêneres."),
        ("20.03", "Serviços de terminais rodoviários, ferroviários, metroviários, movimentação de passageiros e mercadorias, logística e congêneres."),
        ("21.01", "Serviços de registros públicos, cartorários e notariais."),
        ("22.01", "Serviços de exploração de rodovia mediante cobrança de preço ou pedágio, conservação, manutenção, operação, monitoração e assistência aos usuários."),
        ("23.01", "Serviços de programação e comunicação visual, desenho industrial e congêneres."),
        ("24.01", "Serviços de chaveiros, confecção de carimbos, placas, sinalização visual, banners, adesivos e congêneres."),
        ("25.01", "Funerais, inclusive fornecimento de caixão, urna, aluguel de capela, transporte, flores, certidão de óbito, embalsamento e conservação de cadáveres."),
        ("25.02", "Cremação de corpos e partes de corpos cadavéricos."),
        ("25.03", "Planos ou convênio funerários."),
        ("25.04", "Manutenção e conservação de jazigos e cemitérios."),
        ("25.05", "Cessão de uso de espaços em cemitérios para sepultamento."),
        ("26.01", "Serviços de coleta, remessa ou entrega de correspondências, documentos, objetos, bens ou valores, inclusive courrier e congêneres."),
        ("27.01", "Serviços de assistência social."),
        ("28.01", "Serviços de avaliação de bens e serviços de qualquer natureza."),
        ("29.01", "Serviços de biblioteconomia."),
        ("30.01", "Serviços de biologia, biotecnologia e química."),
        ("31.01", "Serviços técnicos em edificações, eletrônica, eletrotécnica, mecânica, telecomunicações e congêneres."),
        ("32.01", "Serviços de desenhos técnicos."),
        ("33.01", "Serviços de desembaraço aduaneiro, comissários, despachantes e congêneres."),
        ("34.01", "Serviços de investigações particulares, detetives e congêneres."),
        ("35.01", "Serviços de reportagem, assessoria de imprensa, jornalismo e relações públicas."),
        ("36.01", "Serviços de meteorologia."),
        ("37.01", "Serviços de artistas, atletas, modelos e manequins."),
        ("38.01", "Serviços de museologia."),
        ("39.01", "Serviços de ourivesaria e lapidação, quando o material for fornecido pelo tomador do serviço."),
        ("40.01", "Obras de arte sob encomenda.")
    };
}
